---

- name: RedHat | Install dependencies packages
  yum: name={{ item }} state=installed
  with_items: "{{ mongodb_packages_dependencies }}"

- name: RedHat | Add source sources
  yum_repository:
    name: mongodb-org-{{ mongodb_version }}
    description: MongoDB Repository
    baseurl: "{{ mongodb_repo_baseurl }}"
    gpgcheck: "{{ mongodb_repo_gpgcheck }}"
    gpgkey: "{{ mongodb_repo_gpgkey }}"

- name: RedHat | Install Packages
  yum: name={{ item }} state=installed
  with_items: "{{ mongodb_packages }}"
