---
- name:         provision sysconfig
  template:
    src:        init/seafile.sysconfig
    dest:       /etc/sysconfig/seafile
    owner:      root
    group:      root
    mode:       0644
  when:         ansible_os_family == "RedHat"
  notify:       restart_seafile

- name:         provision init script
  template:
    src:        init/{{ item.name }}.initd.{{ ansible_os_family }}
    dest:       /etc/init.d/{{ item.name }}
    owner:      root
    group:      root
    mode:       0750
  when:         ansible_os_family in item.os_family
  with_items:   SEAFILE_INIT_SCRIPTS
  notify:       restart_seafile

- name:         provision upstart script
  template:
    src:        init/seafile.conf
    dest:       /etc/init/seafile.conf
    owner:      root
    group:      root
    mode:       0644
  when:         ansible_distribution == "Ubuntu"
  notify:       restart_seafile

- name:         enable init services
  service:
    name:       '{{ item.name }}'
    enabled:    yes
  when:         ansible_os_family in item.os_family
  with_items:   SEAFILE_INIT_SCRIPTS
  notify:       restart_seafile

