---
- name: check supported versions
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full|version_compare(min_ansible_version, '>=')
      - ansible_distribution in SEAFILE_SUPPORTED_DISTRIBUTIONS
      - '".".join(seafile_install_version.split(".")[0:2]) in SEAFILE_SUPPORTED_VERSIONS'
      - seafile_backend in SEAFILE_SUPPORTED_BACKENDS
      - ansible_python_version.startswith('2.6') or ansible_python_version.startswith('2.7')

- name:         install dependencies - deb
  apt:
    name:               '{{ item }}'
    state:              latest
  with_items:   DEPENDENCY_PACKAGES_APT
  when:         ansible_pkg_mgr == 'apt'

- name:         install dependencies - rpm + python 2.6
  yum:
    name:               '{{ item }}'
    state:              latest
  with_items:   DEPENDENCY_PACKAGES_RPM
  when:         ansible_pkg_mgr == 'yum' and ansible_python_version.startswith('2.6')

- name:         install dependencies - rpm + python 2.7
  yum:
    name:               '{{ item }}'
    state:              latest
  with_items:   DEPENDENCY_PACKAGES_RPM
  when:         ansible_pkg_mgr == 'yum' and ansible_python_version.startswith('2.7')

