---
galaxy_info:
  author: "Yosh de Vos"
  description: An Ansible role for install docker and docker-enter.
  license: MIT
  version: 0.1
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
       - all
    - name: Debian
      versions:
       - all
  categories:
    - networking
    - packaging
    - system
dependencies: []
