---

# Upgrade

- name: upgrade sources list
  action: template src=../templates/sources_list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644
  when: upgrade_source_use_template
  tags:
    - common
    - upgrade

- name: upgrade sources list to jessie(stable)
  action: replace dest=/etc/apt/sources.list regexp='(\s+)wheezy(\s+.*)?$' replace='\jessie\3' backup=yes
  when: upgrade_source_use_template == false and replace_source_to_jessie
  tags:
    - common
    - upgrade

# Update all packages to the latest stable version
- apt: upgrade=dist
  when: upgrade_source_use_template or replace_source_to_jessie
  tags:
    - common
    - upgrade

# Update apt cache

- apt: update_cache=yes cache_valid_time=3600
  tags:
    - common
    - update

# Setup hostname

- name: setup hostname
  hostname: name={{ inventory_hostname }}
  when: set_hostname
  tags:
    - common
    - hostname

# Setup default DNS

- name: setup default dns
  action: lineinfile dest=/etc/resolv.conf line="nameserver 8.8.8.8" backup=yes
  when: use_google_dns
  tags:
    - common
    - dns

# Install common packages

- name: install build-essential
  action: apt pkg=build-essential state=installed
  tags:
    - common
    - build

- name: install editor
  action: apt pkg={{ item }} state=installed
  with_items:
    - vim
  tags:
    - common
    - editor

- name: install version control tools
  action: apt pkg={{ item }} state=installed
  with_items:
    - git
  tags:
    - common
    - vcs

- name: install mosh
  action: apt pkg=mosh state=installed
  tags:
    - common
    - mosh

- name: install ranger
  action: apt pkg=ranger state=installed
  tags:
    - common
    - ranger

- name: install imagemagick
  action: apt pkg=imagemagick state=installed
  tags:
    - common
    - imagemagick

- name: install sendmail
  action: apt pkg={{ item }} state=installed
  with_items:
    - sendmail-bin
    - sendmail
  tags:
    - common
    - sendmail

- name: install common python packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
  tags:
    - common
    - python

- name: install supervisor
  action: apt pkg={{ item }} state=installed
  with_items:
    - supervisor
  tags:
    - common
    - python
    - supervisor

- name: install virtualenv
  action: pip name={{ item }} state=present
  with_items:
    - virtualenv
  tags:
    - common
    - python
